BusinessManagementSystemApp/BusinessManagementSystemApp/Controllers/CustomerInfoController.cs
using BusinessManagementSystemApp.BLL.Manager;
using BusinessManagementSystemApp.Models.Models;
using System.Linq;
using System.Web.Mvc;

namespace BusinessManagementSystemApp.Controllers
{
    public class CustomerInfoController : Controller
    {
        CustomerManager _customerManager = new CustomerManager();
        private CustomerModel _customerModel = new CustomerModel();
        // GET: CustomerInfo
        [HttpGet]
        public ActionResult Insert()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Insert(CustomerModel customerModel)
        {

            if (ModelState.IsValid)
            {
                if (_customerManager.Insert(customerModel))
                {
                    ViewBag.SuccessMsg = "Data Saved SuccessFully!";
                }
                else
                {
                    ViewBag.FailMsg = "Data Saved Fail!";
                }
            }
            else
            {
                ViewBag.FailMsg = "Data Validation Fail!";
            }

            return View();
        }
        [HttpGet]
        public ActionResult Update(int Id)
        {
            _customerModel.Id = Id;
            var customer = _customerManager.FindById(_customerModel);
            return View(customer);
        }

        [HttpPost]
        public ActionResult Update(CustomerModel customerModel)
        {
            if (ModelState.IsValid)
            {
                if (_customerManager.Update(customerModel))
                {
                    ViewBag.SuccessMsg = "Data Update SuccessFully!";
                    TempData["SuccessMessage"] = "Data Update SuccessFully!";
                    return RedirectToAction("FindAll");
                }
                else
                {
                    ViewBag.FailMsg = "Data Update Fail!";
                    TempData["SuccessMessage"] = "Data Update Fail!";
                    return RedirectToAction("FindAll");
                    //Response.Redirect("FindAll");
                }
            }
            else
            {
                ViewBag.FailMsg = "Data Validation Fail!";
                Response.Redirect("FindAll");
            }

            return View(customerModel);
        }

        public ActionResult Delete(int Id)
        {
            _customerModel.Id = Id;

            if (_customerManager.Delete(_customerModel))
            {
                ViewBag.SuccessMsg = "Data Delete SuccessFully!";
                Response.Redirect("FindAll");
            }
            else
            {
                ViewBag.FailMsg = "Data Delete Fail!";
                Response.Redirect("FindAll");
            }

            return View();
        }
        [HttpGet]
        public ActionResult FindAll()
        {
            _customerModel.Customers = _customerManager.FindAll();
            return View(_customerModel);
        }
        [HttpPost]
        public ActionResult FindAll(CustomerModel customerModel)
        {
            var customers = _customerManager.FindAll();
            if (customerModel.CustName != null)
            {
                customers = customers.Where(c => c.CustName.ToLower().Contains(customerModel.CustName.ToLower())).ToList();
            }
            customerModel.Customers = customers;
            return View(customerModel);
        }
        public JsonResult IsExist(int CustCode)
        {
            var customer = _customerManager.IsExist(CustCode);

            return Json(customer, JsonRequestBehavior.AllowGet);
        }

    }

}

BusinessManagementSystemApp/BusinessManagementSystemApp/Views/CustomerInfo/Delete.cshtml
@{
    Layout = null;
}
@if (ViewBag.SuccessMsg != null)
{
    <h3 style="font-family:'Times New Roman', Times, serif; color:darkgreen">@ViewBag.SuccessMsg</h3>
}
@if (ViewBag.FailMsg != null)
{
    <h3 style="font-family:'Times New Roman', Times, serif; color:brown">@ViewBag.FailMsg</h3>
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <div>
    </div>
</body>
</html>
@section scripts{

    <script src="~/Scripts/SweetAlert.js"></script>
    <script src="~/Scripts/sweetalert.min.js"></script>
    <link href="~/Styles/sweetalert.css" rel="stylesheet" />

    <script>
            $(function () {

                var successMessage = '@TempData["SuccessMessage"]'
                if (successMessage != '')
                    swal({
                        position: 'top-end',
                        type: 'success',
                        title:successMessage,
                        showConfirmButton: false,
                        timer: 1500
                    })

                 var successMessage = '@TempData["SuccessDeleteMessage"]'
                if (successMessage != '')
                    swal( {
                        position: 'top-end',
                        type: 'error',
                        title: successMessage,
                        showConfirmButton: false,
                        timer: 1500
                    });
        });

    </script>
}

BusinessManagementSystemApp/BusinessManagementSystemApp/Views/CustomerInfo/FindAll.cshtml
@model BusinessManagementSystemApp.Models.Models.CustomerModel
@{
    Layout = "~/Views/Shared/Dashboard.cshtml";
}
<div class="row">
    <div class="page-title">
        <div class="title_left">
            <h3><small>Search by customer name</small></h3>
        </div>

        <div class="title_right">
            <form method="post">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                    <div class="input-group">
                        <input type="text" name="CustName" value="@Model.CustName" class="form-control" placeholder="Search for...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">Go!</button>
                        </span>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Customer Information List</h2>
                <div class="navbar-right">
                    @*<a href="Insert" class="btn btn-primary btn-sm"><i class="fa fa-plus-square"></i>Add</a>*@
                    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
                        <i class="fa fa-plus-square"></i>Add
                    </button>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>@Html.LabelFor(c => c.CustCode)</th>
                            <th>@Html.LabelFor(c => c.CustName)</th>
                            <th>@Html.LabelFor(c => c.CustEmail)</th>
                            <th>@Html.LabelFor(c => c.CustContact)</th>
                            <th>@Html.LabelFor(c => c.CustAddress)</th>
                            <th>@Html.LabelFor(c => c.CustLoyaltyPoints)</th>
                            <th style="text-align:center;">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{ int sl = 1;}
                        @foreach (var customer in Model.Customers)
                        {
                            <tr>
                                <th scope="row">@(sl++)</th>
                                <td>@customer.CustCode</td>
                                <td>@customer.CustName</td>
                                <td>@customer.CustEmail</td>
                                <td>@customer.CustContact</td>
                                <td>@customer.CustAddress</td>
                                <td>@customer.CustLoyaltyPoints</td>
                                <td style="text-align:center;"><a href="Update?Id=@customer.Id"><i class='fa fa-edit'></i></a>&nbsp;||&nbsp<a href="Delete?Id=@customer.Id"><i class="fa fa-trash"></i></a></td>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>
        </div>
    </div>

    <div class="clearfix"></div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <form class="form-horizontal form-label-left" novalidate action="@Url.Action("Insert","CustomerInfo")" method="post" enctype="multipart/form-data">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Customer Add Form</h4>
                    </div>
                    <div class="modal-body">
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="CustCode">
                                @Html.LabelFor(c => c.CustCode) <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(c => c.CustCode, null, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12", required = "required", placeholder = "1001" })
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="CustName">
                                @Html.LabelFor(c => c.CustName) <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(c => c.CustName, null, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12", required = "required", placeholder = "both name(s) e.g Md Mehedi" })
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="CustEmail">
                                @Html.LabelFor(c => c.CustEmail) <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(c => c.CustEmail, null, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12", required = "required", placeholder = "example@gmail.com" })
                            </div>
                        </div>

                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="CustContact">
                                @Html.LabelFor(c => c.CustContact) <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(c => c.CustContact, null, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12", required = "required", placeholder = "01316347466" })
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="number">
                                @Html.LabelFor(c => c.CustLoyaltyPoints) <span class="required"></span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(c => c.CustLoyaltyPoints, null, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12", placeholder = "500" })
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="CustAddress">
                                @Html.LabelFor(c => c.CustAddress) <span class="required"></span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextAreaFor(c => c.CustAddress, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                            </div>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    </div>
                </div>
            </div>
        </form>
    </div>

BusinessManagementSystemApp/BusinessManagementSystemApp/Views/CustomerInfo/Insert.cshtml
@model BusinessManagementSystemApp.Models.Models.CustomerModel
@{
Layout = "~/Views/Shared/Dashboard.cshtml";
}
<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_content">
                        <form class="form-horizontal form-label-left" novalidate action="" method="post" enctype="multipart/form-data">
                            <span class="section">Customer Information</span>

                            <div class="item form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="CustCode">
                                    @Html.LabelFor(c=>c.CustCode) <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @Html.TextBoxFor(c => c.CustCode, null, htmlAttributes: new { @class = "form-control", required = "required", placeholder = "10001" })
                                    @Html.ValidationMessageFor(c => c.CustCode, null, new { @class = "text-danger" })
                                    <span class="text-danger" id="isExist"></span>
                                    <span class="text-danger" id="CodeLength"></span>
                                </div>
                            </div>
                            <div class="item form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="CustName">
                                    @Html.LabelFor(c => c.CustName) <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @Html.TextBoxFor(c => c.CustName, null, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12", required = "required", placeholder = "name(s) e.g Md Mehedi" })
                                    @Html.ValidationMessageFor(c => c.CustName, null, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="item form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="CustEmail">
                                    @Html.LabelFor(c => c.CustEmail) <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @Html.TextBoxFor(c => c.CustEmail,null,htmlAttributes:new { @class = "form-control col-md-7 col-xs-12", required = "required", placeholder = "example@gmail.com" })
                                </div>
                            </div>

                            <div class="item form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="CustContact">
                                    @Html.LabelFor(c => c.CustContact) <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @Html.TextBoxFor(c => c.CustContact, null, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12", required = "required", placeholder = "01316347466" })
                                    @Html.ValidationMessageFor(c => c.CustContact, null, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="item form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="number">
                                    @Html.LabelFor(c => c.CustLoyaltyPoints) <span class="required"></span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @Html.TextBoxFor(c => c.CustLoyaltyPoints, null, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12", placeholder = "500" })
                                </div>
                            </div>
                            <div class="item form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="CustAddress">
                                    @Html.LabelFor(c => c.CustAddress) <span class="required"></span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @Html.TextAreaFor(c => c.CustAddress, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12"})
                                </div>
                            </div>
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-3">
                                    <input id="Save" type="submit" class="btn btn-success" value="Submit">
                                    <button type="button" class="btn btn-primary">Cancel</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- /page content -->
@section Scripts{
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script>
        $(document).ready(function () {

            $('#CustCode').on('keyup', function () {
                var CustCode = $('#CustCode').val();
                var CodeLength = $('#CustCode').val().length;
                if (CodeLength < 5) {
                    $('#CodeLength').text("Please Enter Minimum Length 5!");
                    $('#Save').attr("disabled", true);
                } else {
                    $('#CodeLength').text("");
                    $('#Save').attr("disabled", false);
                }
                $.ajax(
                    {
                        url: "/CustomerInfo/IsExist",
                        type: "POST",
                        data: { CustCode: CustCode},
                        success: (data) => {
                            if(data.CustCode != ""){
                                console.log(data.CustCode);
                                $('#isExist').text("This Code Is Exist!");
                                $('#Save').attr("disabled", true);
                            }else{
                                $('#isExist').text("This Code No Exist!");
                                $('#Save').attr("disabled", false);
                                //$('#isExist').removeClass("text-danger");
                                //$('#isExist').addClass("text-success");
                               
                            }
        
                        }
                    });
            });
                    var successMessage = '@TempData["SuccessMessage"]'
            if (successMessage != '')
                swal({
                    position: 'top-end',
                    type: 'success',
                    title: successMessage,
                    showConfirmButton: false,
                    timer: 1500
                })

                 var successMessage = '@TempData["SuccessDeleteMessage"]'
            if (successMessage != '')
                swal({
                    position: 'top-end',
                    type: 'error',
                    title: successMessage,
                    showConfirmButton: false,
                    timer: 1500
                });
        });
    </script>

}            

    

BusinessManagementSystemApp/BusinessManagementSystemApp/Views/CustomerInfo/Update.cshtml
@model BusinessManagementSystemApp.Models.Models.CustomerModel
@{
    Layout = "~/Views/Shared/Dashboard.cshtml";
}

<div class="right_col" role="main">
    <div class="">
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li>
                                <a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <form class="form-horizontal form-label-left" novalidate action="" method="post" enctype="multipart/form-data">
                            <span class="section">Customer Information</span>

                            <div class="item form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="CustCode">
                                    @Html.LabelFor(c => c.CustCode) <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @Html.TextBoxFor(c => c.CustCode, Model.CustCode.ToString(), htmlAttributes: new { @class = "form-control col-md-7 col-xs-12", required = "required", placeholder = "1001" })
                                </div>
                            </div>
                            <div class="item form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="CustName">
                                    @Html.LabelFor(c => c.CustName) <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @Html.TextBoxFor(c => c.CustName, Model.CustName, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12", required = "required", placeholder = "both name(s) e.g Md Mehedi" })
                                </div>
                            </div>
                            <div class="item form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="CustEmail">
                                    @Html.LabelFor(c => c.CustEmail) <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @Html.TextBoxFor(c => c.CustEmail, Model.CustEmail, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12", required = "required", placeholder = "example@gmail.com" })
                                </div>
                            </div>

                            <div class="item form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="CustContact">
                                    @Html.LabelFor(c => c.CustContact) <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @Html.TextBoxFor(c => c.CustContact, Model.CustContact.ToString(), htmlAttributes: new { @class = "form-control col-md-7 col-xs-12", required = "required", placeholder = "01316347466" })
                                </div>
                            </div>
                            <div class="item form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="number">
                                    @Html.LabelFor(c => c.CustLoyaltyPoints) <span class="required"></span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @Html.TextBoxFor(c => c.CustLoyaltyPoints, Model.CustLoyaltyPoints.ToString(), htmlAttributes: new { @class = "form-control col-md-7 col-xs-12", placeholder = "500" })
                                </div>
                            </div>
                            <div class="item form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="CustAddress">
                                    @Html.LabelFor(c => c.CustAddress) <span class="required"></span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @Html.TextAreaFor(c => c.CustAddress, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                                </div>
                            </div>
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-3">
                                    <button id="Save" type="submit" class="btn btn-success">Submit</button>
                                    <button type="button" class="btn btn-primary">Cancel</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{

    <script src="~/Scripts/SweetAlert.js"></script>
    <script src="~/Scripts/sweetalert.min.js"></script>
    <link href="~/Styles/sweetalert.css" rel="stylesheet" />

    <script>
            $(function () {

                var successMessage = '@TempData["SuccessMessage"]'
                if (successMessage != '')
                    swal({
                        position: 'top-end',
                        type: 'success',
                        title:successMessage,
                        showConfirmButton: false,
                        timer: 1500
                    })

                 var successMessage = '@TempData["SuccessDeleteMessage"]'
                if (successMessage != '')
                    swal( {
                        position: 'top-end',
                        type: 'error',
                        title: successMessage,
                        showConfirmButton: false,
                        timer: 1500
                    });
        });

    </script>
}